version: "3.7"
services:
  mqtt:
    container_name: mqtt
    build: 
      context: .
      dockerfile: dockerfiles/broker.Dockerfile
    network_mode: host
    restart: unless-stopped
  influxdb:
    container_name: influxdb
    build: 
      context: .
      dockerfile: dockerfiles/influxdb.Dockerfile
    network_mode: host
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=p455w0rd
      - DOCKER_INFLUXDB_INIT_ORG=isd
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=SUPERTOKEN!
